use_frameworks!

target 'UIExpandableTableViewCard_Example' do
  pod 'UIExpandableTableViewCard', :path => '../'

  target 'UIExpandableTableViewCard_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
